"""Generate API documentation into docs/api (no 'later')."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from lebanese_franco_factory.core.paths import repo_root


def generate_api_docs() -> Path:
    """Render package API docs with pdoc into docs/api/."""
    out = repo_root() / "docs" / "api"
    out.mkdir(parents=True, exist_ok=True)
    pkg = "lebanese_franco_factory"
    cmd = [
        sys.executable,
        "-m",
        "pdoc",
        "-o",
        str(out),
        pkg,
    ]
    subprocess.run(cmd, check=True, cwd=str(repo_root()))
    # Stable landing note
    index = out / "index.md"
    if not index.exists():
        (out / "README.md").write_text(
            "# API docs\n\nGenerated by `lff docs` / `pdoc`.\n"
            "Open `lebanese_franco_factory.html` (or the folder index produced by pdoc).\n",
            encoding="utf-8",
        )
    return out
