"""Checksums, splits, and dataset card generation."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def write_checksums(paths: list[Path], out_file: Path) -> dict[str, str]:
    checksums: dict[str, str] = {}
    lines: list[str] = []
    for path in paths:
        digest = sha256_file(path)
        checksums[path.name] = digest
        lines.append(f"{digest}  {path.name}")
    out_file.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    return checksums


def split_records(
    records: list[dict[str, Any]],
    ratios: dict[str, float] | None = None,
) -> dict[str, list[dict[str, Any]]]:
    ratios = ratios or {"train": 0.98, "validation": 0.01, "test": 0.01}
    n = len(records)
    if n == 0:
        return {"train": [], "validation": [], "test": []}
    n_val = max(1, int(n * ratios.get("validation", 0.01))) if n >= 100 else max(0, min(1, n // 50))
    n_test = max(1, int(n * ratios.get("test", 0.01))) if n >= 100 else max(0, min(1, n // 50))
    if n < 3:
        return {"train": records, "validation": [], "test": []}
    # ensure train gets the rest
    while n_val + n_test >= n:
        if n_test > 0:
            n_test -= 1
        elif n_val > 0:
            n_val -= 1
        else:
            break
    train = records[: n - n_val - n_test]
    validation = records[n - n_val - n_test : n - n_test]
    test = records[n - n_test :] if n_test else []
    return {"train": train, "validation": validation, "test": test}


def write_dataset_card(path: Path, meta: dict[str, Any]) -> None:
    families = meta.get("families", {})
    lines = [
        "---",
        f"pretty_name: Lebanese Franco Dataset {meta.get('version', 'v0.1')}",
        "license: apache-2.0",
        "language:",
        "  - ar",
        "  - en",
        "tags:",
        "  - lebanese",
        "  - arabizi",
        "  - franco",
        "---",
        "",
        f"# Lebanese Franco Dataset {meta.get('version', 'v0.1')}",
        "",
        "Generated by [Lebanese-Franco-Factory](https://github.com/JulianoSaad/Lebanese-Franco-Factory).",
        "",
        "## Sizes",
        "",
    ]
    for family, size in families.items():
        lines.append(f"- `{family}`: {size}")
    lines.extend(
        [
            "",
            "## Files",
            "",
            "See `manifests/` and `SHA256SUMS`. Small samples are under `samples/`.",
            "",
            f"Factory commit: `{meta.get('factory_commit')}`",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def write_metadata_json(path: Path, meta: dict[str, Any]) -> None:
    path.write_text(json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
